name: Run Arbitrage Bot

on:
  schedule:
    - cron: '*/10 * * * *'  # каждые 10 минут
  workflow_dispatch:        # можно запускать вручную

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python bot.py
